### ISSUE TITLE
Move here the existing integrations from the main Falco repository

### ISSUE THREAD

**Issue by leodido** [falcosecurity/contrib#2]
**Motivation**

As discussed with the whole community during [yesterday's community call](https://github.com/falcosecurity/community/blob/master/meeting-notes/2020-04-15.md), we're going to move out from the main Falco repository its `integrations/` directory.

This relates to the more broader discussion about Falco's official artifacts (https://github.com/falcosecurity/falco/issues/1114).

**Feature**

Move here the `integrations/` directory of Falco.

/assign @maxgio92 

Wait for https://github.com/falcosecurity/test-infra/pull/113 to be merged in, thanks! 🥇

**Comment by leogr** [comment]
Cross-linking https://github.com/falcosecurity/falco/issues/1145

Once the content from the `integrations/` directory is moved here, I will clean up the falco repo.

**Comment by maxgio92** [comment]
Hi all,
I just opened a PR merely starting from moving the whole `integrations/` directory in the root of this project; I think that could be as good as little starting point, what do you think?

I also read the interesting discussion led by @kris-nova about the Falco artifacts and as discusses also in the last call I totally understand the point and agree.
Because of this I'll keep in mind the real scope of Falco in the whole stack when thinking about the benefis that the integrations - i.e. Kubernetes resources, but not only - could bring and to not to force technologies where they shouldn't. 

Thank you all
