### ISSUE TITLE
Cleanup of on-top-of-Kubernetes solutions

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/contrib#7]
**Motivation**

I think there are too ways to deploy Falco on top of Kubernetes (deployment VS daemonset + with-RBAC VS without-RBAC + Falco slim container image VS Falco "full" container image).

**Feature**

I'd maintain only the daemonset solution since the driverloader should run on every node, with RBAC enabled since it is the default authorization mechanism for apps in k8s. 
Furthermore, since this is not an official method to deploy Falco (kernelspace and userspace components), I think that it's better to keep it simple. 

**Additional context**

The Falco images are going to be under review; see [here](https://github.com/falcosecurity/falco/issues/1171) for details.

/kind feature

**Comment by leogr** [comment]
Has that been fixed? 
I believe so, except for the slim image that should be fixed by https://github.com/falcosecurity/contrib/issues/5

Furthermore, [integrations/k8s-using-deployment](https://github.com/falcosecurity/contrib/tree/master/integrations/k8s-using-deployment) seems to be a different use case that we should still keep, IMO.

**Comment by maxgio92** [comment]
Yes, I agree. As the deployment solution should still be in place this issue can be considered fixed for me too.
